name: mqtt_humidity_level
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3'

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^9.6.1
  liquid_progress_indicator:
    path: lib/liquid_progress_indicator

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
